services:
  medapi_postgres:
    image: postgres
    ports:
      - 5566:5432
    env_file: ./postgres/.env
    volumes:
      # Mount for postgres data persistence e.g.
      # - ./prod_postgres_data:/var/lib/postgresql/data
      # Mount host folder for seed - postgres will run all .sql files in this folder on startup
      # If a db already exists, init files will not run - so to reseed, the container / volume need to be removed and recreated
      - ./postgres/seed_data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  coreapi:
    build: ./core_api
    env_file: ./core_api/.env
    volumes:
      - ./core_api/src/:/app/src/
    command: npm run dev

  client:
    environment:
      - VITE_API_URL=http://localhost:5000/coreapi
    build: ./client
    volumes:
      - ./client/src:/app/src
    command: npm run dev

  gateway:
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - coreapi
