services:
  api:
    build: ./core_api
    env_file: ./core_api/.env
    restart: always
    ports:
      - 4000:4000
    # volumes:
    #   - ./api/src/:/app/src/
    command: npm run dev


  # client:
  #   env_file: ./client/.env
  #   build: ./client
  #   volumes:
  #     - ./client/src:/app/src
  #   restart: always
  #   command: npm run dev
  #   ports:
  #     - 5173:5173

  gateway:
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      # - client
      - api

