http {
    server{

    listen 80;

    location /coreapi{
      proxy_pass http://staging-coreapi:4000;
      proxy_http_version 1.1;
      access_log off;
    }
    # The extra slashes ensures the path is not appended to the proxy_pass URL.
    location /mailer/{
      proxy_pass http://mailer:3310/;
      proxy_http_version 1.1;
      access_log off;
    }

    location / {
      proxy_pass http://staging-client:5173;
      proxy_http_version 1.1;
      proxy_set_header Connection $http_connection;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_cache_bypass $http_upgrade;
    }

  }
}
events{
#nothing here
}
