# .github/workflows/staging-client.yml
name: Compile and push all images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: ['staged']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # login with Docker
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          # generate some credentials from Dockerhub and store them into the repo secrets
          # Those credentials are defined as github environment variables ($RepoURL/settings/secrets/actions)
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # prepare buildx for docker
      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx

      # build an push the client
      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: ./client
          file: ./client/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_CLIENT_IMAGE_NAME }}:latest

        # build an push the core api
      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: ./core_api
          file: ./core_api/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_CORE_API_IMAGE_NAME }}:latest

        # build an push the mailer
      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: ./mailer
          file: ./mailer/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_MAILER_IMAGE_NAME }}:latest

        # build an push the uploader
        - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: ./upload
          file: ./upload/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_UPLOAD_IMAGE_NAME }}:latest
